(GH-181) `pct install` to namespaced location
puppetlabs/pdkgo pull request #197
Opened 2021-08-27 12:37 UTC by da-ar

2021-09-01 09:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/pdkgo?pullRequest=197) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/pdkgo?pullRequest=197) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/pdkgo?pullRequest=197) it.</sub>

2021-09-07 10:52 UTC, sanfrancrisko requested changes

2021-09-07 10:52 UTC, sanfrancrisko commented on internal/pkg/pct/install_test.go
> +		// This test cannot be performed due to a bug in aferos MemMapFs
Can this test be re-enabled given [your observation](https://github.com/spf13/afero/issues/319)?

2021-09-07 17:55 UTC, michaeltlombardi approved these changes

2021-09-07 17:55 UTC, merged