(WIP) Draft of PCT Install & Quick Start docs
puppetlabs/pdkgo pull request #80
Opened 2021-06-02 17:41 UTC by sanfrancrisko

2021-06-02 23:29 UTC, jpogran requested changes

2021-06-02 23:29 UTC, jpogran commented on README.md
> +## Installing
These new headers need to be added to the TOC at the begining

2021-06-02 23:29 UTC, jpogran commented on README.md
> +Use the `install.[ps1|sh]` script, depending upon your OS:
```suggestion
While the PCT is in early release, we provide an archive and a simple script to unpack it. When we move closer to a full release we will add a platform specific installer. Use the `install.[ps1|sh]` script, depending upon your OS:
```

2021-06-03 10:43 UTC, da-ar requested changes
Change the commit from "draft of". 
In future avoid WIP or Draft in the commit and just use a draft PR to signify work in progress.

Apart from that it looks great, nice work

2021-06-03 10:53 UTC, sanfrancrisko commented
> Change the commit from "draft of".
> In future avoid WIP or Draft in the commit and just use a draft PR to signify work in progress.
> 
> Apart from that it looks great, nice work

Good catch - forgot to rename that in the rebase

2021-06-03 11:19 UTC, da-ar approved these changes

2021-06-03 11:42 UTC, jpogran approved these changes

2021-06-03 11:42 UTC, merged